### ISSUE TITLE
I might have a way to loop even more icons

### ISSUE THREAD

**Issue by rathod-sahaab** [cyberalien/line-md#10]
Instead of using duration and delay/begin we time using values array which gives us more freedom regarding timing and repeatability.

Below is customised code for external link. Pay special attention to `values` and notice that `dur`  is same in all

UPDATE 1: _Got some time_
Explaining how it works

Values split the dur equally among the elements if you want a bigger part to take more time just fill more of it's values and adjust by interpolating it yourself. If you want one animation to start only after other, then change the value after the index by which first has finished.

```
animation1: 42 21  0 0 0 0
animation2: 12 12 12 0 0 0
animation3:  8  8  8 8 0 0
```

animation 2 starts after 1 as values only change from a index after 1 stops
similarly animation 3 starts after 2

```svg

<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
	><g
		fill="none"
		stroke="currentColor"
		stroke-linecap="round"
		stroke-linejoin="round"
		stroke-width="2"
		><path stroke-dasharray="42" stroke-dashoffset="42" d="M11 5H5V19H19V13"
			><animate
				fill="freeze"
				attributeName="stroke-dashoffset"
				dur="2.4s"
				values="42;0;0;0;0;0"
				repeatCount="indefinite"
			/>
		</path>
		<path stroke-dasharray="12" stroke-dashoffset="12" d="M13 11L20 4"
			><animate
				fill="freeze"
				attributeName="stroke-dashoffset"
				dur="2.4s"
				values="12;12;0;0;0;0"
				repeatCount="indefinite"
			/>
		</path>
		<path stroke-dasharray="8" stroke-dashoffset="8" d="M21 3H15M21 3V9">
			<animate
				fill="freeze"
				attributeName="stroke-dashoffset"
				dur="2.4s"
				values="8;8;8;0;0;0"
				repeatCount="indefinite"
			/>
		</path></g
	>
</svg>


```

**Comment by cyberalien** [comment]
Sorry, I'm very confused what you are trying to show there.

Restarting stroke animation after a delay is not something I'd consider adding. As for that code, there is a `keyTimes` attribute, which can be used to adjust timing instead of repeating same value multiple times.

**Comment by rathod-sahaab** [comment]
Yeah `keyTimes` is much better than the mathematics I suggest along the lines of time quantum yadayada.

So now the only suggestion is that for all icons to be loop-able we should keep the animation durations the same and play with keytimes to be infinitely repeatable. This is not a must but makes changing the duration easy.

This is assuming that icons like external link are not intentionally (not loopable).
