### ISSUE TITLE
Location icon

### ISSUE THREAD

**Issue by joseehilton147** [cyberalien/line-md#11]
Can you please make the location item? I think will be a such add to this wonderful library

https://icon-sets.iconify.design/mdi/location/

**Comment by cyberalien** [comment]
Added `map-marker` icon, both outline and filled. For experiment I've added a bounce animation in `-alt` versions of icons.

![demo-1696784433938](https://github.com/cyberalien/line-md/assets/822287/77146ad2-c518-4901-93fd-cce90086171f)

**Comment by joseehilton147** [comment]
you are the best
