### ISSUE TITLE
briefcase icon

### ISSUE THREAD

**Issue by joseehilton147** [cyberalien/line-md#12]
I dont know if you prefer to keep all on same issue, or open new issue for every request, but a briefcase icon is a must too, again, im using your library on a personal project to train my front end skills and is keeping beautiful

https://icon-sets.iconify.design/mdi/briefcase/

**Comment by cyberalien** [comment]
Added to `dev` branch, will be added to main repo tomorrow.

**Comment by joseehilton147** [comment]
perfect, ty so much

how hard is too make this icons? i could help making some PR for missing icons based on MDI icons

**Comment by cyberalien** [comment]
It isn't simple. In MDI all icons use fill, so icons aren't usable. Each icon needs to be redesigned to make sure it uses stroke, which can then be animated.

When designing icon, I need to make sure stroke starts and ends at points where I want to start/end animation, so often icons need to be designed not as closed shapes, but open ones and manually adjusted. This requires knowledge of path commands.

Animations are added manually. There aren't any tools for animating icons. Animating stroke requires calculating path length, though I do have script that does it automatically, it still needs to be added manually.

I've been considering making something to help animate icons, but that would require massive amount of work and there is very little demand for that, so I don't think making any tools for animation is feasible.

**Comment by joseehilton147** [comment]
i understand, so much much thanks for what you are doing.

**Comment by cyberalien** [comment]
Thanks!

Just added about 30 more icons for map category, so category wouldn't be so small.
