### ISSUE TITLE
calendar with a number or cake to reminder age or birthdate

### ISSUE THREAD

**Issue by joseehilton147** [cyberalien/line-md#13]
Line MD already have a calendar icon but i think isn't very suitable for all things related to date, like birthdates for example, something more like a cake icon or a calendar with a number will be more suitable, like one of this for example:

https://icon-sets.iconify.design/ph/calendar/

https://icon-sets.iconify.design/mdi/cake-variant-outline/

**Comment by cyberalien** [comment]
Not sure about calendar with numbers, it is a bit tricky to create as line.

However, cake is doable. Added: https://icon-sets.iconify.design/line-md/?query=cake
