### ISSUE TITLE
[Icon Requests] YouTube, Pinterest, Clubhouse, Pixelfed & PayPal

### ISSUE THREAD

**Issue by zcraber** [cyberalien/line-md#14]
Would love to see animated icons for YouTube, Pinterest, Clubhouse, Pixelfed and PayPal! Thank you.

**Comment by cyberalien** [comment]
I was going to post that I've added icon (added to `dev` branch so far, will be in `main` branch tomorrow), then noticed that title changed.

So YouTube is done, I'll see about others. Problem with many of those icons is there is not much to animate, but I'll try.

![demo-1696952798794](https://github.com/cyberalien/line-md/assets/822287/293f8acb-8684-445a-8515-f56e4d764e6b)

**Comment by zcraber** [comment]
Thank you! It'd be nice if you could update the README with details of how users can contribute to this.

**Comment by cyberalien** [comment]
Added Pixelfed icon, but I can't think of a way to animate other icons on that list.

There are no stroke versions of those icons, recreating them as stroke icons won't work, so stroke animation can't be used. Can't think of any other way to animate them.

**Comment by cyberalien** [comment]
> Thank you! It'd be nice if you could update the README with details of how users can contribute to this.

Unfortunately it is not easy. There are no tools for animating icons. I wrote a long explanation here: https://github.com/cyberalien/line-md/issues/12#issuecomment-1753026338

Current development process requires environment with apache+php (needed for scripts used for designing/previewing icons), good knowledge of SVG, knowing how to work with vectors in software that can be used for pixel perfect vector design such as Figma or Sketch.

**Comment by zcraber** [comment]
Thanks for the details.
