### ISSUE TITLE
Sign in sign out icons

### ISSUE THREAD

**Issue by joseehilton147** [cyberalien/line-md#15]
Could you please include these icons?

https://icon-sets.iconify.design/mdi/login/
https://icon-sets.iconify.design/mdi/logout/

IMO if could be two versions on logout, like on MDI and inverted arrow, like you are going out directyion.

Anyway, ty

**Comment by cyberalien** [comment]
Added: https://github.com/cyberalien/line-md/commit/4a6ca636ef47024bd00b6a463ebe0a76b75980c1
