### ISSUE TITLE
settings icon

### ISSUE THREAD

**Issue by joseehilton147** [cyberalien/line-md#16]
i think 3 types of icons can fit in this description, this:

https://icon-sets.iconify.design/mdi/tune-variant/

this:

https://icon-sets.iconify.design/mdi/account-cog-outline/

and this:

https://icon-sets.iconify.design/mdi/cog/

would be lovely if you could include them.

PS: if u prefer i can open only one issue and keep adding the requests i think should be a great improvement to this library there, up to you, anyway, thanks again.

**Comment by cyberalien** [comment]
Added cog icon: https://github.com/cyberalien/line-md/commit/b956fc5e92c3979fafe9369800f32ee5caebe06f

It was very tricky to create, I tried new idea on how to do animations and it worked.
