### ISSUE TITLE
Icon Request: Odysee, LBRY & PeerTube

### ISSUE THREAD

**Issue by zcraber** [cyberalien/line-md#17]

**Comment by cyberalien** [comment]
PeerTube was added just hours before your issue (but wasn't pushed to GitHub until now): https://github.com/cyberalien/line-md/commit/bccf6e7d7cffb6de8696a9993c6014aaec4fd663

Odysee icon is too complex to animate.

LBRY can probably be animated, I'll try it.

**Comment by cyberalien** [comment]
Sorry, LBRY icon is not usable. It is too thin for 24x24 icon. It would work nicely as at least 40x40, but that won't be suitable for this icon set.

So only PeerTube icon can be animated and added to this icon set.
