### ISSUE TITLE
[Bugs] Issue with sunny-outline , sunny-outline-loop & github-loop

### ISSUE THREAD

**Issue by psynyde** [cyberalien/line-md#2]
So `github-loop` has a weird issue where it leaves a thin line where the eyes are located
#### preview :
![git-loop-icon](https://media.discordapp.net/attachments/971427533025333328/996480631238312058/unknown.png)

As for the `sunny-outline` & `sunny-outline-loop` they are giving result of their twotone variant
#### preview:

![sunny-outline](https://media.discordapp.net/attachments/971427533025333328/996482488023134239/unknown.png)

code: `<Icon v-if="isDark" icon="line-md:sunny-outline" class="text-xl text-gray-100"/>`
Environment: Windows, vue3 & vite
Package: `iconify/vue`

**Comment by cyberalien** [comment]
Thanks for reporting!

Bug in `sunny-outline` and `sunny-outline-loop` was fixed about 30 minutes ago. It will appear on Iconify after next icon sets update tomorrow.

`github-loop` issue is indeed weird. I'll test it.

**Comment by cyberalien** [comment]
`github-loop` fixed. It was caused by pixel bleeding that happens when icon is scaled. New mask accounts for that and hides 1 pixel above/below eye.
