### ISSUE TITLE
[Icon Request] A looping moon icon

### ISSUE THREAD

**Issue by inu20** [cyberalien/line-md#4]
Hi! Thanks for your lovely icons. I really like them especially the sun, and just wondering is it possible to have a looping style for moon icons, perhaps a moon with shining stars.

Many thanks ^-^

**Comment by cyberalien** [comment]
Thanks!

That's a good idea.

**Comment by cyberalien** [comment]
Something like this?

![moon-filled-loop](https://user-images.githubusercontent.com/822287/193236312-eacd593b-f986-455d-a3df-a232427b9c40.svg)

**Comment by cyberalien** [comment]
I wasn't happy with that icon: star fading in seems rather dull. Stars can't be replaced because they are used in other moon icons, so instead created couple of alternative moon icons:


![moon-alt-loop](https://user-images.githubusercontent.com/822287/193257494-9bdc0a57-b66c-44d8-8b92-f4c6c8848404.svg)
![moon-filled-alt-loop](https://user-images.githubusercontent.com/822287/193257499-3dba3e48-a4eb-4a03-8dea-0305280c2566.svg)

**Comment by cyberalien** [comment]
Hm, not fan of that attempt either. Lines are easier to animate than stars, but they seem too large.

Another attempt with thin lines:
![moon-alt-loop](https://user-images.githubusercontent.com/822287/193308066-06bff73a-0e39-4f26-b3d5-b998d0e177f3.svg)

Which ones do you prefer?

**Comment by cyberalien** [comment]
...or this with smaller lines?

![moon-alt2-loop](https://user-images.githubusercontent.com/822287/193308642-b8f59c6f-f423-42cd-a790-b02fd8fae906.svg)

**Comment by anurag-roy** [comment]
I think I like the last one most, the star size and thickness is perfect, not taking away attention from the moon. ✨

**Comment by cyberalien** [comment]
Sorry for slow response. Icons have been added almost 2 weeks ago, but forgot to reply and close this issue.

There are 12 animated moon icons. One of icons: https://icon-sets.iconify.design/line-md/moon-filled-loop/

To see all icons, in filters above icons list enter "moon" in search and click "Looping Animation" filter.

**Comment by inu20** [comment]
Hi! sorry for late response.
I can't believe that I miss this, all of icons are so cute! The last one is perfect! And the first one also looks great!

**Comment by cyberalien** [comment]
Thanks!
