### ISSUE TITLE
[Icon request] Star icon

### ISSUE THREAD

**Issue by jrvgr** [cyberalien/line-md#5]
Hello! I would love to have star variants of the heart icon. Your icons look great so far, keep up the great work!

**Comment by cyberalien** [comment]
Thanks.

Added bunch of star icons: https://github.com/cyberalien/line-md/commit/5a1562950e8f934f97f3542d07bc1a293d79634a

They'll be available in Iconify tomorrow after update script runs.

**Comment by jrvgr** [comment]
closed by 5a15629

**Comment by jrvgr** [comment]
Thanks a lot btw!
