### ISSUE TITLE
Request to update twitter icon

### ISSUE THREAD

**Issue by adydetra** [cyberalien/line-md#7]
i need a new twitter icon (X icon) with the animation

**Comment by cyberalien** [comment]
Added 2 versions.

Gif showing animation:

![twitter-x](https://github.com/cyberalien/line-md/assets/822287/af6647fa-9ec7-4e56-a6ca-172c0c05f026)

Animation runs only once on load. There is nothing in that icon to animate after that.

**Comment by adydetra** [comment]
Perfect!

Sorry, the icon is not yet available on Iconify. Maybe the icon set repo ([this](https://github.com/iconify/icon-sets/blob/master/json/line-md.json)) hasn't been updated yet.

And btw **thank you**, I'll close this issues.

**Comment by cyberalien** [comment]
Iconify sets are updated several times a week, but it is not instant. Next update is scheduled for tomorrow morning, so icon will be there tomorrow.

**Comment by cyberalien** [comment]
Slightly changed timing in `twitter-x-alt` icon. First part of animation is a bit slower and there is a small delay between animations.

![twitter-x-v2](https://github.com/cyberalien/line-md/assets/822287/78194c66-0289-4733-88d2-5ea58ad6323e)
