### ISSUE TITLE
[Icon request] eye

### ISSUE THREAD

**Issue by rdwz** [cyberalien/line-md#8]
![Screenshot 2023-08-23 205046](https://github.com/cyberalien/line-md/assets/8125196/af74d9f1-d6bd-485f-b2cd-d9a97ff15f87)

On Github as used on the `Watch` counter/button or in general for views.
Material example: https://icon-sets.iconify.design/mdi/eye-outline/

**Comment by cyberalien** [comment]
Sorry for delay. I'm hoping to get to this in a few days.

**Comment by cyberalien** [comment]
Added few icons: `watch` and `watch-off` with `-twotone` variations and with extra icons that have infinite animation (eye blinking every 6 seconds and `off` line slightly moving)

But just noticed that I forgot to add `watch-loop` and `watch-twotone-loop` variations. I'll add them in next release, probably later today.

Gif preview:
![demo-1693372350721](https://github.com/cyberalien/line-md/assets/822287/c0924369-4509-404b-89c7-54dee6b51865)

**Comment by cyberalien** [comment]
> But just noticed that I forgot to add `watch-loop` and `watch-twotone-loop` variations. I'll add them in next release, probably later today.

Added.

**Comment by rdwz** [comment]
Thank you so much!
