### ISSUE TITLE
[Request] Checkbox Icons

### ISSUE THREAD

**Issue by YaroKasear** [cyberalien/line-md#9]
Really like this icon set, is there a chance that there could be a checkbox set to go along with the radio icon set to differentiate between single-choice option sets and multiple-choice option sets? I don't have the skill to do that myself but would love to use this set in a project of mine.

**Comment by cyberalien** [comment]
Sorry for delay. I'm hoping to get to this in a few days.

**Comment by cyberalien** [comment]
Added square versions of all circle icons in `Interface` category. Didn't do the same for arrows and alerts yet, will do it this week.

Filter icons by `square` to see all new icons.

Preview GIF of few icons:
![demo-1693371991654](https://github.com/cyberalien/line-md/assets/822287/9a5fa689-e626-4f5c-a596-17d656780da5)

**Comment by cyberalien** [comment]
> Added square versions of all circle icons in `Interface` category. Didn't do the same for arrows and alerts yet, will do it this week.

Added. Now all circle icons have square variations.

**Comment by YaroKasear** [comment]
Thank you very much!
